#!/bin/sh
#echo "run from ${BASH_SOURCE[0]}"
set -o noclobber
export PATH=~/bin:$PATH
export PATH=~/bin/spec:$PATH # TODO: hopefully tmp, try think o sth better
export XDG_CACHE_HOME=~/cache
export XDG_CONFIG_HOME=~/etc
export XDG_DATA_HOME=~/sha
export XDG_STATE_HOME=~/state
. "$XDG_CONFIG_HOME/sh/vars"
. "$XDG_CONFIG_HOME/sh/alias"
[ -x "$XDG_CONFIG_HOME/sh/motd" ] && "$XDG_CONFIG_HOME/sh/motd"
[ -x "$XDG_CONFIG_HOME/sh/jtong7" ] && "$XDG_CONFIG_HOME/sh/jtong7"
true
