#!/bin/sh
set -o noclobber
export PATH=$HOME/bin:$PATH
export XDG_CACHE_HOME=$HOME/cache
export XDG_CONFIG_HOME=$HOME/etc
export XDG_DATA_HOME=$HOME/sha
export XDG_STATE_HOME=$HOME/state
. "$XDG_CONFIG_HOME/sh/vars"
. "$XDG_CONFIG_HOME/sh/alias"
"$XDG_CONFIG_HOME/sh/motd"
