#!/bin/sh

# DON'T TOUCH THIS LINE
. ~/.standard_bashrc #/usr/local/rcfiles/Bashrc.global

umask 077

export PATH=~/go/bin/:$PATH
export GOROOT=~/go
#PS1='\u@\h:\w $ '

#alias 415='. ~cmput415/415-resources/415env.sh'
#vicmd() { "${EDITOR:-vi}" "$(command -v "$1")"; }
