#!/bin/sh
# dep: lolcat, tsv.py
readonly bold=$(printf '\033[1m')
readonly  end=$(printf '\033[0m')
alias p='printf %s\\n'
phead() {
	printf "%s## %s%s\n" "$bold" "$1" "$end"
}

#phead 'IMPORTANT NOTICES'
#lolcat "$XDG_CONFIG_HOME/sh/notices.txt"
#echo

#phead 'SCHED'
#cat "$HOME/doc/me/sched2.txt" | tail -n +2 | lolcat
#echo

#phead 'TODO'
#neldoreth | lolcat
#echo

motd_reminder() {
	phead 'rwl; ___ pyr (neldore0); SLEEP !!!!!!!!!!!!!!'
	sed -n '/^## ls rwl$/,${/^- /p}' ~stairs/doc/me/rwl.md |
		tr -d ' -~' | paste -d '\0' - - - | paste -d ',' - - | sed 's/,/，/' |
		head -n 3 | lolcat
	echo
}

motd_vim_swap() {
	readonly swapdir=$XDG_CACHE_HOME/vim/swap
	[ "$(p "$swapdir"/*)" != "$swapdir/*" ] || return
	readonly pswp='
for f do
	printf %s\\t%s\\n \
		"$(file "$f" | sed -E "s/.*, pid ([0-9]+),.*/\\1/")" "$f"
done
	'
	phead 'VIM SWAP DIR'
	find "$swapdir" -type f -exec sh -c "$pswp" _ {} + | lolcat
	echo
}

motd_bday() {
	readonly bday=$(~/bin/spec/bday)
	[ -n "$bday" ] || return
	phead 'UPCOMING BIRTHDAYS'
	p "$bday"
	echo
}

main() {
	motd_reminder
	motd_vim_swap
	motd_bday
	p '# ; das Gesetz, der Pyrit, der Schlaf'
}

main
