#!/bin/sh
# Only ever modify master copy on arch:!
# dep: file (idk if this `file` behav is std)
# TODO: mv % ~/bin/
readonly LF='
'
alias p='printf %s\\n'

fatal() {
	>&2 p "$0: $1"
	exit 1
}

main() {
	ck_newline
	ck_colon # fnames w colon mess up parsing `file` output
	ck_crlf
}

ck_newline() {
	files=$(find . -name "*$LF*")
	[ -z "$files" ] || fatal "these fnames contain newlines:$LF$files"
}

ck_colon() {
	files=$(find . -name '*:*')
	[ -z "$files" ] || fatal "these fnames contain colons:$LF$files"
}

ck_crlf() {
	# TODO: test this fn
	# TODO: bf mv
	files=$(git diff --cached --name-only --diff-filter=ACM)
	[ -z "$files" ] && return 0
	IFS=$LF
	# shellcheck disable=SC2086
	files=$(file -- $files |
		awk -F : '{ fname = $1; $1 = ""; if (/CRLF/) print fname; }')
	[ -z "$files" ] || fatal "these files use CRLF:$LF$files"
}

main
